apiVersion: v1
kind: Secret
metadata:
  name: secretforfunction
  labels:
    app: secretforfunction
type: Opaque
data:
  clientid: <YOUR OAUTH CLIENT ID - BASE64 ENCODED!>
  clientsecret: <YOUR OAUTH CLIENT SECRET - BASE64 ENCODED!>
  durabelfuncendpoint: <YOUR ENDPOINT - BASE64 ENCODED!>
